/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  Assert: () => Assert,
  Helper: () => Helper,
  Paths: () => Paths,
  default: () => MyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// node_modules/uuid/dist/esm-browser/stringify.js
var byteToHex = [];
for (i = 0; i < 256; ++i) {
  byteToHex.push((i + 256).toString(16).slice(1));
}
var i;
function unsafeStringify(arr, offset = 0) {
  return (byteToHex[arr[offset + 0]] + byteToHex[arr[offset + 1]] + byteToHex[arr[offset + 2]] + byteToHex[arr[offset + 3]] + "-" + byteToHex[arr[offset + 4]] + byteToHex[arr[offset + 5]] + "-" + byteToHex[arr[offset + 6]] + byteToHex[arr[offset + 7]] + "-" + byteToHex[arr[offset + 8]] + byteToHex[arr[offset + 9]] + "-" + byteToHex[arr[offset + 10]] + byteToHex[arr[offset + 11]] + byteToHex[arr[offset + 12]] + byteToHex[arr[offset + 13]] + byteToHex[arr[offset + 14]] + byteToHex[arr[offset + 15]]).toLowerCase();
}

// node_modules/uuid/dist/esm-browser/rng.js
var getRandomValues;
var rnds8 = new Uint8Array(16);
function rng() {
  if (!getRandomValues) {
    getRandomValues = typeof crypto !== "undefined" && crypto.getRandomValues && crypto.getRandomValues.bind(crypto);
    if (!getRandomValues) {
      throw new Error("crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported");
    }
  }
  return getRandomValues(rnds8);
}

// node_modules/uuid/dist/esm-browser/native.js
var randomUUID = typeof crypto !== "undefined" && crypto.randomUUID && crypto.randomUUID.bind(crypto);
var native_default = {
  randomUUID
};

// node_modules/uuid/dist/esm-browser/v4.js
function v4(options, buf, offset) {
  if (native_default.randomUUID && !buf && !options) {
    return native_default.randomUUID();
  }
  options = options || {};
  var rnds = options.random || (options.rng || rng)();
  rnds[6] = rnds[6] & 15 | 64;
  rnds[8] = rnds[8] & 63 | 128;
  if (buf) {
    offset = offset || 0;
    for (var i = 0; i < 16; ++i) {
      buf[offset + i] = rnds[i];
    }
    return buf;
  }
  return unsafeStringify(rnds);
}
var v4_default = v4;

// main.ts
var INDEX_NOTE_PATH = "Notes/eec0a297-982c-471c-9748-4943ec45fe94.md";
var IndexLinkSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, entries, sourcePath) {
    super(app);
    this.entries = entries;
    this.sourcePath = sourcePath;
    this.setPlaceholder("Search index links...");
    this.emptyStateText = "No matching index link";
  }
  getItems() {
    return this.entries;
  }
  getItemText(item) {
    return item.alias;
  }
  getFileFromLeaf(leaf) {
    let file = void 0;
    try {
      file = leaf.view.file;
    } catch (e) {
      return void 0;
    }
    return this.app.vault.getAbstractFileByPath(file);
  }
  openViewInNewTabIfNotOpened(name) {
    const f = this.app.vault.getAbstractFileByPath(name);
    if (f === void 0 || f === null) {
      console.warn(`file not found ${name}`);
      return;
    }
    const active = this.app.workspace.getLeaf();
    const root = active.parent;
    let found = false;
    let node = void 0;
    const emptyTabs = [];
    for (const leaf of root.children) {
      const file = this.getFileFromLeaf(leaf);
      if (file === void 0 || file === null) {
        emptyTabs.push(leaf);
        continue;
      }
      if (file.name === f.name) {
        found = true;
        node = leaf;
      }
    }
    if (!found) {
      if (emptyTabs.length > 0) {
        node = emptyTabs[0];
      } else {
        this.app.workspace.createLeafInParent(
          root,
          root.children.length + 1
        );
        node = root.children[root.children.length - 1];
      }
    }
    node.openFile(f, { active: true });
  }
  onChooseItem(item) {
    this.openViewInNewTabIfNotOpened(`${item.target}.md`);
  }
};
var dayShort = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
var monthShort = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec"
];
var DEFAULT_SETTINGS = {
  mySetting: "default",
  managedHeadingAliases: {}
};
var MyPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.vaultContent = [];
    this.vaultContentDict = {};
    this.headingAliasTimers = /* @__PURE__ */ new Map();
    this.headingAliasSyncs = /* @__PURE__ */ new Map();
    this.aliasSettingsSaveTimer = void 0;
  }
  openViewInNewTabIfNotOpened(name) {
    const f = this.app.vault.getAbstractFileByPath(name);
    if (f === void 0 || f === null) {
      console.warn(`file not found ${name}`);
      return;
    }
    const active = this.app.workspace.getLeaf();
    const root = active.parent;
    let found = false;
    let node = void 0;
    const emptyTabs = [];
    for (const leaf of root.children) {
      const file = this.getFileFromLeaf(leaf);
      if (file === void 0 || file === null) {
        emptyTabs.push(leaf);
        continue;
      }
      if (file.name === f.name) {
        found = true;
        node = leaf;
      }
    }
    if (!found) {
      if (emptyTabs.length > 0) {
        node = emptyTabs[0];
      } else {
        this.app.workspace.createLeafInParent(
          root,
          root.children.length + 1
        );
        node = root.children[root.children.length - 1];
      }
    }
    node.openFile(f, { active: true });
  }
  getFileFromLeaf(leaf) {
    let file = void 0;
    try {
      file = leaf.view.file;
    } catch (e) {
      return void 0;
    }
    return this.app.vault.getAbstractFileByPath(file);
  }
  extractUUIDFromLink(link) {
    Assert.True(
      link.length >= 36,
      `extractUUIDFromLink: Invalid parameter type: link: "${link}"`
    );
    Assert.True(
      Helper.isUUID(link.slice(0, 36)),
      `extractUUIDFromLink: Invalid parameter type: link: "${link}"`
    );
    if (link.length === 36) {
      return link;
    } else {
      return link.slice(0, 36);
    }
  }
  getFileFromUUID(_id) {
    return this.vaultContentDict[_id];
  }
  getFileCacheFromUUID(_id) {
    const f = this.vaultContentDict[_id];
    if (f === void 0) {
      return void 0;
    }
    return this.app.metadataCache.getFileCache(f);
  }
  getIndexLinkEntries() {
    var _a, _b;
    const indexFile = this.app.vault.getAbstractFileByPath(INDEX_NOTE_PATH);
    if (!(indexFile instanceof import_obsidian.TFile)) {
      new import_obsidian.Notice(`Index note not found: ${INDEX_NOTE_PATH}`);
      return null;
    }
    const cache = this.app.metadataCache.getFileCache(indexFile);
    if (cache === null || cache === void 0) {
      new import_obsidian.Notice(`Index note metadata is not ready: ${INDEX_NOTE_PATH}`);
      return null;
    }
    const entries = /* @__PURE__ */ new Map();
    for (const link of (_a = cache.links) != null ? _a : []) {
      const alias = (_b = link.displayText) == null ? void 0 : _b.trim();
      if (alias === void 0 || alias === "") {
        continue;
      }
      const entry = { target: link.link, alias };
      entries.set(`${entry.target}\0${entry.alias}`, entry);
    }
    return Array.from(entries.values());
  }
  isHeadingAliasFile(file) {
    return file.extension === "md" && (file.path.startsWith("Notes/") || file.path.startsWith("Verbatim/"));
  }
  getFirstHeadingAlias(cache) {
    var _a;
    const heading = (_a = cache.headings) == null ? void 0 : _a.find((item) => item.level === 1);
    const alias = heading == null ? void 0 : heading.heading.trim();
    return alias === "" ? void 0 : alias;
  }
  getNextHeadingAliases(existingAliases, previousManagedAlias, desiredAlias) {
    const aliases = previousManagedAlias !== void 0 ? existingAliases.filter(
      (alias) => alias !== previousManagedAlias
    ) : [...existingAliases];
    const desiredAliasIsManual = desiredAlias !== void 0 && aliases.includes(desiredAlias);
    if (desiredAlias !== void 0 && !desiredAliasIsManual) {
      aliases.push(desiredAlias);
    }
    return {
      aliases,
      managedAlias: desiredAlias !== void 0 && !desiredAliasIsManual ? desiredAlias : void 0
    };
  }
  aliasesAreEqual(left, right) {
    return left.length === right.length && left.every((alias, index) => alias === right[index]);
  }
  setManagedHeadingAlias(path, alias) {
    const current = this.settings.managedHeadingAliases[path];
    if (current === alias) {
      return;
    }
    if (alias === void 0) {
      delete this.settings.managedHeadingAliases[path];
    } else {
      this.settings.managedHeadingAliases[path] = alias;
    }
    this.scheduleAliasSettingsSave();
  }
  scheduleAliasSettingsSave() {
    if (this.aliasSettingsSaveTimer !== void 0) {
      window.clearTimeout(this.aliasSettingsSaveTimer);
    }
    this.aliasSettingsSaveTimer = window.setTimeout(() => {
      this.aliasSettingsSaveTimer = void 0;
      this.saveSettings().catch((error) => {
        console.error("Unable to save managed heading aliases", error);
      });
    }, 500);
  }
  async reconcileHeadingAlias(file) {
    var _a;
    const previousManagedAlias = this.settings.managedHeadingAliases[file.path];
    if (file.extension !== "md") {
      this.setManagedHeadingAlias(file.path, void 0);
      return;
    }
    const cache = this.app.metadataCache.getFileCache(file);
    if (cache === null || cache === void 0) {
      return;
    }
    const desiredAlias = this.isHeadingAliasFile(file) ? this.getFirstHeadingAlias(cache) : void 0;
    const existingAliases = (_a = (0, import_obsidian.parseFrontMatterAliases)(cache.frontmatter)) != null ? _a : [];
    const next = this.getNextHeadingAliases(
      existingAliases,
      previousManagedAlias,
      desiredAlias
    );
    let nextManagedAlias = next.managedAlias;
    if (!this.aliasesAreEqual(existingAliases, next.aliases)) {
      await this.app.fileManager.processFrontMatter(
        file,
        (frontmatter) => {
          var _a2;
          const currentAliases = (_a2 = (0, import_obsidian.parseFrontMatterAliases)(frontmatter)) != null ? _a2 : [];
          const currentNext = this.getNextHeadingAliases(
            currentAliases,
            previousManagedAlias,
            desiredAlias
          );
          nextManagedAlias = currentNext.managedAlias;
          if (currentNext.aliases.length === 0) {
            delete frontmatter.aliases;
          } else {
            frontmatter.aliases = currentNext.aliases;
          }
        }
      );
    }
    this.setManagedHeadingAlias(file.path, nextManagedAlias);
  }
  queueHeadingAliasSync(file, delay = 300) {
    const path = file.path;
    const existingTimer = this.headingAliasTimers.get(path);
    if (existingTimer !== void 0) {
      window.clearTimeout(existingTimer);
    }
    const timer = window.setTimeout(() => {
      var _a;
      this.headingAliasTimers.delete(path);
      const previousSync = (_a = this.headingAliasSyncs.get(path)) != null ? _a : Promise.resolve();
      const currentSync = previousSync.catch(() => void 0).then(() => this.reconcileHeadingAlias(file));
      this.headingAliasSyncs.set(path, currentSync);
      currentSync.catch((error) => {
        console.error(
          `Unable to synchronize heading alias for: ${file.path}`,
          error
        );
      }).finally(() => {
        if (this.headingAliasSyncs.get(path) === currentSync) {
          this.headingAliasSyncs.delete(path);
        }
      });
    }, delay);
    this.headingAliasTimers.set(path, timer);
  }
  async reconcileAllHeadingAliases() {
    var _a, _b;
    const files = this.app.vault.getMarkdownFiles();
    const filesByPath = new Map(files.map((file) => [file.path, file]));
    const filesByName = /* @__PURE__ */ new Map();
    for (const file of files) {
      const matches = (_a = filesByName.get(file.name)) != null ? _a : [];
      matches.push(file);
      filesByName.set(file.name, matches);
    }
    for (const path of Object.keys(this.settings.managedHeadingAliases)) {
      if (filesByPath.has(path)) {
        continue;
      }
      const name = path.split("/").last();
      const matches = name === void 0 ? [] : (_b = filesByName.get(name)) != null ? _b : [];
      if (matches.length === 1 && this.settings.managedHeadingAliases[matches[0].path] === void 0) {
        this.settings.managedHeadingAliases[matches[0].path] = this.settings.managedHeadingAliases[path];
      }
      this.setManagedHeadingAlias(path, void 0);
    }
    for (const file of files) {
      if (this.isHeadingAliasFile(file) || this.settings.managedHeadingAliases[file.path] !== void 0) {
        await this.reconcileHeadingAlias(file);
      }
    }
  }
  openPdfExternally(file, subpath) {
    var _a;
    if (!Helper.isUUID(file.parent.name)) {
      new import_obsidian.Notice(`Invalid asset location: ${file.path}`);
      return;
    }
    if (file.parent.parent === void 0 || file.parent.parent.name !== "Assets") {
      new import_obsidian.Notice(`Invalid asset location: ${file.path}`);
      return;
    }
    const pageMatch = /^#page=([1-9]\d*)(?:&|$)/i.exec(subpath);
    const adapter = this.app.vault.adapter;
    const path = `${adapter.basePath}/${file.parent.path}`;
    const { spawn } = require("child_process");
    const args = [
      "--user",
      `--working-directory=${path}`,
      "--",
      "/usr/bin/zathura",
      `--page=${(_a = pageMatch == null ? void 0 : pageMatch[1]) != null ? _a : "1"}`,
      file.name
    ];
    const child = spawn("systemd-run", args, {
      stdio: "ignore"
    });
    let errorReported = false;
    const reportError = () => {
      if (!errorReported) {
        errorReported = true;
        new import_obsidian.Notice(`Unable to open PDF: ${file.name}`);
      }
    };
    child.on("error", reportError);
    child.on("close", (code) => {
      if (code !== 0) {
        reportError();
      }
    });
  }
  async onload() {
    var _a, _b;
    console.log("gonext - onload()");
    await this.loadSettings();
    this.dv = this.app.plugins.plugins.dataview.api;
    this.files = {};
    this.api = {};
    window.gonext = {
      // @ts-ignore
      state: (_b = (_a = window.gonext) == null ? void 0 : _a.state) != null ? _b : {},
      // @ts-ignore
      app: this.app
    };
    (0, import_obsidian.addIcon)(
      "GoNextIcon",
      `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><path fill="currentColor" d="M20 12V2h2v10zm4 0V2h2v10zm4 0V2h2v10zm-12 8a3.912 3.912 0 0 1-4-4a3.912 3.912 0 0 1 4-4v-2a6 6 0 1 0 6 6h-2a3.912 3.912 0 0 1-4 4"></path><path fill="currentColor" d="M28.893 18.454L26.098 16l-1.318 1.504l2.792 2.452l-2.36 4.088l-3.427-1.16a9.032 9.032 0 0 1-2.714 1.565L18.36 28h-4.72l-.71-3.55a9.095 9.095 0 0 1-2.695-1.572l-3.447 1.166l-2.36-4.088l2.725-2.395a8.926 8.926 0 0 1-.007-3.128l-2.718-2.39l2.36-4.087l3.427 1.16A9.03 9.03 0 0 1 12.93 7.55L13.64 4H16V2h-2.36a2 2 0 0 0-1.961 1.608l-.504 2.519a10.967 10.967 0 0 0-1.327.753l-2.42-.819a1.998 1.998 0 0 0-2.372.895l-2.36 4.088a2 2 0 0 0 .411 2.502l1.931 1.697C5.021 15.495 5 15.745 5 16c0 .258.01.513.028.766l-1.92 1.688a2 2 0 0 0-.413 2.502l2.36 4.088a1.998 1.998 0 0 0 2.374.895l2.434-.824a10.974 10.974 0 0 0 1.312.759l.503 2.518A2 2 0 0 0 13.64 30h4.72a2 2 0 0 0 1.961-1.608l.504-2.519a10.967 10.967 0 0 0 1.327-.753l2.419.818a1.998 1.998 0 0 0 2.373-.894l2.36-4.088a2 2 0 0 0-.411-2.502"></path></svg>`
    );
    this.addCommand({
      id: "search-index-links",
      name: "Search Index Links",
      callback: () => {
        const entries = this.getIndexLinkEntries();
        if (entries === null) {
          return;
        }
        new IndexLinkSuggestModal(
          this.app,
          entries,
          INDEX_NOTE_PATH
        ).open();
      }
    });
    this.addCommand({
      id: "open-assets",
      name: "Open Assets",
      // @ts-ignore
      callback: async () => {
        const leaf = this.app.workspace.getLeaf();
        const file = this.getFileFromLeaf(leaf);
        const adapter = this.app.vault.adapter;
        const vaultDir = adapter.basePath;
        const uuid = file.basename;
        const parent = file.parent.name;
        const cache = this.getFileCacheFromUUID(uuid);
        if (cache === void 0) {
          console.warn(`Possible invalid frontmatter for: ${uuid}`);
          return;
        }
        let name = this.getResourceName(cache);
        if (name === void 0) {
          name = uuid;
        }
        if (parent === "Verbatim") {
          if (!await adapter.exists(`${Paths.Assets}/${uuid}/`)) {
            await this.app.vault.adapter.mkdir(
              `${Paths.Assets}/${uuid}/`
            );
          }
          const assetPath = `${vaultDir}/${Paths.Assets}/${uuid}/`;
          const { shell } = require("electron");
          shell.showItemInFolder(assetPath);
        } else if (parent === Paths.Actions) {
          const _uuid = this.findResourceNamed(name, Paths.Notes);
          if (_uuid !== "") {
            await leaf.openFile(this.getFileFromUUID(_uuid));
          } else {
            new import_obsidian.Notice(`No Log Entry for: ${name}`);
          }
        } else if (parent === Paths.Notes) {
          const _uuid = this.findResourceNamed(name, Paths.Actions);
          if (_uuid !== "") {
            await leaf.openFile(this.getFileFromUUID(_uuid));
          } else {
            new import_obsidian.Notice(`No Action for: ${name}`);
          }
        } else if (parent !== Paths.Actions && parent !== Paths.Notes) {
          new import_obsidian.Notice(`Unsuported type: ${parent}`);
        }
      }
    });
    this.addCommand({
      id: "properties-toggle",
      name: "Properties: toggle Visible/Hidden",
      callback: () => {
        const cur = this.app.vault.getConfig("propertiesInDocument");
        const next = cur === "hidden" ? "source" : "hidden";
        this.app.vault.setConfig("propertiesInDocument", next);
      }
    });
    this.addCommand({
      id: "goto-definition",
      name: "Goto Definition",
      // @ts-ignore
      editorCallback: (editor) => {
        const cursor = editor.getCursor();
        const line = editor.getLine(cursor.line);
        const links = [];
        const collect = (regexp, cursorOffset, extractTarget) => {
          let match = void 0;
          while ((match = regexp.exec(line)) !== null) {
            const value = match[0];
            links.push({
              from: match.index,
              to: match.index + value.length,
              cursor: match.index + cursorOffset(value),
              target: extractTarget(value)
            });
          }
        };
        collect(
          /!?\[\[[^\]]+\]\]/g,
          (value) => value.startsWith("![[") ? 3 : 2,
          (value) => {
            const start = value.startsWith("![[") ? 3 : 2;
            return value.slice(start, -2).split("|", 1)[0].trim();
          }
        );
        collect(
          /!?\[[^\]\n]*\]\([^)]+\)/g,
          (value) => value.indexOf("](") + 2,
          (value) => {
            const start = value.indexOf("](") + 2;
            let target = value.slice(start, -1).trim();
            if (target.startsWith("<") && target.endsWith(">")) {
              target = target.slice(1, -1);
            }
            return target;
          }
        );
        collect(
          /<https?:\/\/[^>\s]+>/g,
          () => 1,
          (value) => value.slice(1, -1)
        );
        collect(
          /https?:\/\/[^\s<>()]+/g,
          () => 1,
          (value) => value
        );
        const candidates = links.filter((link2) => {
          return !links.some(
            (other) => other !== link2 && other.from <= link2.from && other.to >= link2.to && other.to - other.from > link2.to - link2.from
          );
        });
        const distance = (link2) => {
          if (cursor.ch < link2.from) {
            return link2.from - cursor.ch;
          }
          if (cursor.ch > link2.to) {
            return cursor.ch - link2.to;
          }
          return 0;
        };
        const link = candidates.find(
          (link2) => link2.from <= cursor.ch && cursor.ch <= link2.to
        ) || candidates.sort(
          (a, b) => distance(a) - distance(b) || a.from - b.from
        )[0];
        if (link === void 0) {
          new import_obsidian.Notice(`No link found`);
          return;
        }
        const sourceFile = this.app.workspace.getActiveFile();
        if (sourceFile !== null) {
          const linktext = (0, import_obsidian.parseLinktext)(link.target);
          let linkedFile = void 0;
          try {
            linkedFile = this.app.metadataCache.getFirstLinkpathDest(
              linktext.path,
              sourceFile.path
            );
          } catch (e) {
            linkedFile = void 0;
          }
          if ((linkedFile == null ? void 0 : linkedFile.extension.toLowerCase()) === "pdf") {
            this.openPdfExternally(linkedFile, linktext.subpath);
            return;
          }
        }
        editor.focus();
        editor.setCursor(cursor.line, link.cursor);
        this.app.commands.executeCommandById("editor:follow-link");
      }
    });
    this.addCommand({
      id: "goto-definition-new-leaf",
      name: "Goto Definition Open in New Leaf",
      // @ts-ignore
      editorCallback: (editor) => {
        const cursor = editor.getCursor();
        const line = editor.getLine(cursor.line);
        const links = [];
        const collect = (regexp, cursorOffset) => {
          let match = void 0;
          while ((match = regexp.exec(line)) !== null) {
            const value = match[0];
            links.push({
              from: match.index,
              to: match.index + value.length,
              cursor: match.index + cursorOffset(value)
            });
          }
        };
        collect(
          /!?\[\[[^\]]+\]\]/g,
          (value) => value.startsWith("![[") ? 3 : 2
        );
        collect(
          /!?\[[^\]\n]*\]\([^)]+\)/g,
          (value) => value.indexOf("](") + 2
        );
        collect(/<https?:\/\/[^>\s]+>/g, () => 1);
        collect(/https?:\/\/[^\s<>()]+/g, () => 1);
        const candidates = links.filter((link2) => {
          return !links.some(
            (other) => other !== link2 && other.from <= link2.from && other.to >= link2.to && other.to - other.from > link2.to - link2.from
          );
        });
        const distance = (link2) => {
          if (cursor.ch < link2.from) {
            return link2.from - cursor.ch;
          }
          if (cursor.ch > link2.to) {
            return cursor.ch - link2.to;
          }
          return 0;
        };
        const link = candidates.find(
          (link2) => link2.from <= cursor.ch && cursor.ch <= link2.to
        ) || candidates.sort(
          (a, b) => distance(a) - distance(b) || a.from - b.from
        )[0];
        if (link === void 0) {
          new import_obsidian.Notice(`No link found`);
          return;
        }
        editor.focus();
        editor.setCursor(cursor.line, link.cursor);
        const activeLeaf = this.app.workspace.getLeaf();
        const root = activeLeaf.parent;
        const leaves = [...root.children];
        this.app.commands.executeCommandById(
          "editor:open-link-in-new-leaf"
        );
        let retry = 0;
        const activateNewLeaf = () => {
          const leaf = root.children.find(
            (leaf2) => !leaves.includes(leaf2)
          );
          if (leaf !== void 0) {
            this.app.workspace.setActiveLeaf(leaf, { focus: true });
            return;
          }
          if (retry < 10) {
            retry += 1;
            setTimeout(activateNewLeaf, 50);
          }
        };
        setTimeout(activateNewLeaf, 0);
      }
    });
    this.addCommand({
      id: "goto-next",
      name: "Goto Next",
      // @ts-ignore
      callback: async () => {
        const dv = this.app.plugins.plugins.dataview.api;
        const leaf = this.app.workspace.getLeaf();
        const file = this.getFileFromLeaf(leaf);
        const uuid = file.basename;
        const parent = file.parent.name;
        const cache = this.getFileCacheFromUUID(uuid);
        if (cache === void 0) {
          console.warn(`Possible invalid frontmatter for: ${uuid}`);
          return;
        }
        let name = this.getResourceName(cache);
        if (name === void 0 || !Helper.isDate(name)) {
          new import_obsidian.Notice(`Expected format yyyy-mm-dd, got: ${name}`);
          return;
        }
        const dt = new Date(name);
        let closest = void 0;
        if (parent !== Paths.Actions && parent !== Paths.Notes) {
          new import_obsidian.Notice(`Unsuported type: ${parent}`);
          return;
        }
        let _closest = 2147483647 * 1e3;
        let _closestUuid = void 0;
        dv.pages(`"${parent}"`).where((page) => {
          const _uuid = page.file.name;
          const _cache = this.getFileCacheFromUUID(_uuid);
          const _name = this.getResourceName(_cache);
          if (_name === void 0) {
            return false;
          }
          if (!Helper.isDate(_name)) {
            return false;
          }
          const _dt = new Date(_name);
          if (_dt.getTime() > dt.getTime() && _dt.getTime() < _closest) {
            _closestUuid = _uuid;
            _closest = _dt.getTime();
          }
          return false;
        });
        Assert.True(_closestUuid !== void 0, `Next was not found`);
        await leaf.openFile(this.getFileFromUUID(_closestUuid));
      }
    });
    this.addCommand({
      id: "goto-prev",
      name: "Goto Prev",
      // @ts-ignore
      callback: async () => {
        const dv = this.app.plugins.plugins.dataview.api;
        console.log("goto-prev");
        const leaf = this.app.workspace.getLeaf();
        const file = this.getFileFromLeaf(leaf);
        const uuid = file.basename;
        const parent = file.parent.name;
        const cache = this.getFileCacheFromUUID(uuid);
        if (cache === void 0) {
          new import_obsidian.Notice(`Possible invalid frontmatter for: ${uuid}`);
          return;
        }
        const name = this.getResourceName(cache);
        if (name === void 0 || !Helper.isDate(name)) {
          new import_obsidian.Notice(`Expected format yyyy-mm-dd, got: ${name}`);
          return;
        }
        const dt = new Date(name);
        let closest = void 0;
        let _closest = 0;
        let _closestUuid = void 0;
        if (parent !== Paths.Actions && parent !== Paths.Notes) {
          new import_obsidian.Notice(`Unsuported type: ${parent}`);
          return;
        }
        dv.pages(`"${parent}"`).where((page) => {
          const _uuid = page.file.name;
          const _cache = this.getFileCacheFromUUID(_uuid);
          const _name = this.getResourceName(_cache);
          if (_name === void 0) {
            return false;
          }
          if (!Helper.isDate(_name)) {
            return false;
          }
          const _dt = new Date(_name);
          if (_dt.getTime() < dt.getTime() && _dt.getTime() > _closest) {
            _closest = _dt.getTime();
            _closestUuid = _uuid;
          }
          return false;
        });
        Assert.True(_closestUuid !== void 0, `Next was not found`);
        await leaf.openFile(this.getFileFromUUID(_closestUuid));
      }
    });
    this.addCommand({
      id: "open-index",
      name: "Open Index",
      // @ts-ignore
      callback: () => {
        this.openViewInNewTabIfNotOpened(
          "Notes/eec0a297-982c-471c-9748-4943ec45fe94.md"
        );
      }
    });
    this.addCommand({
      id: "open-journal",
      name: "Open Journal",
      // @ts-ignore
      callback: () => {
        this.openViewInNewTabIfNotOpened(
          "Notes/a66c1ed1-3022-4197-9ade-152b138813d9.md"
        );
      }
    });
    this.addCommand({
      id: "open-inbox",
      name: "Open Inbox",
      // @ts-ignore
      callback: () => {
        this.openViewInNewTabIfNotOpened(
          "Notes/8c7aad2a-b67f-44b7-86fd-27a50410be65.md"
        );
      }
    });
    this.addCommand({
      id: "open-planning",
      name: "Open Planning",
      // @ts-ignore
      callback: () => {
        this.openViewInNewTabIfNotOpened(
          "Notes/db5a4532-9025-404b-84ab-85e571884e2d.md"
        );
      }
    });
    this.addCommand({
      id: "open-next_actions",
      name: "Open Next Actions",
      // @ts-ignore
      callback: () => {
        this.openViewInNewTabIfNotOpened(
          "Notes/ab7aec92-2273-40bc-9632-da70937b5575.md"
        );
      }
    });
    this.addCommand({
      id: "open-someday_maybe",
      name: "Open Someday Maybe",
      // @ts-ignore
      callback: () => {
        this.openViewInNewTabIfNotOpened(
          "Notes/e7b605b9-4d3a-4c17-bf4e-e7f1a51f7a30.md"
        );
      }
    });
    this.addCommand({
      id: "open-waiting_for",
      name: "Open Waiting For",
      // @ts-ignore
      callback: () => {
        this.openViewInNewTabIfNotOpened(
          "Notes/7a13d7ac-732b-4cec-91f0-1498c824b82e.md"
        );
      }
    });
    this.addCommand({
      id: "open-todays-log",
      name: "Open Today's Logs",
      // @ts-ignore
      callback: () => {
        const now = new Date();
        const nowIso = now.toISOString().slice(0, 10);
        if (!this.loadNoteNamed(nowIso)) {
          this.note(nowIso);
        }
      }
    });
    this.addCommand({
      id: "check-duplicates",
      name: "Check for Duplicates",
      // @ts-ignore
      callback: () => {
        const res = {};
        const dv = this.app.plugins.plugins.dataview.api;
        const pages = dv.pages(`"${Paths.Notes}"`);
        for (const page of pages) {
          const uuid = page.file.name;
          const cache = this.getFileCacheFromUUID(uuid);
          if (cache === void 0) {
            console.warn(
              `Possible invalid frontmatter for: ${uuid}`
            );
            return;
          }
          const name = this.getResourceName(cache);
          if (name === void 0) {
            continue;
          }
          if (!Helper.isDate(name)) {
            continue;
          }
          if (res[name] === void 0 || res[name] === null) {
            res[name] = [uuid];
          } else {
            res[name].push(uuid);
          }
        }
        const keys = Object.keys(res);
        keys.sort();
        for (const key of keys) {
          if (res[key].length > 1) {
            console.log(key);
            for (const page of res[key]) {
              console.log(`	${page}`);
            }
          }
        }
      }
    });
    this.addCommand({
      id: "open-yesterdays-logs",
      name: "Open Yesterday's Logs",
      // @ts-ignore
      callback: () => {
        const now = new Date();
        now.setDate(now.getDate() - 1);
        const nowIso = now.toISOString().slice(0, 10);
        this.loadNoteNamed(nowIso);
      }
    });
    this.addCommand({
      id: "open-todays-daily",
      name: "Open Today's Daily",
      // @ts-ignore
      callback: () => {
        const now = new Date();
        const nowIso = now.toISOString().slice(0, 10);
        this.loadActionNamed(nowIso);
      }
    });
    this.addCommand({
      id: "open-tomorrows-daily",
      name: "Open Tomorrow's Daily",
      // @ts-ignore
      callback: () => {
        const now = new Date();
        now.setDate(now.getDate() + 1);
        const nowIso = now.toISOString().slice(0, 10);
        this.loadActionNamed(nowIso);
      }
    });
    this.addCommand({
      id: "open-yesterdays-daily",
      name: "Open Yesterday's Daily",
      // @ts-ignore
      callback: () => {
        const now = new Date();
        now.setDate(now.getDate() - 1);
        const nowIso = now.toISOString().slice(0, 10);
        this.loadActionNamed(nowIso);
      }
    });
    this.addCommand({
      id: "generate-note",
      name: "Generate Note",
      // @ts-ignore
      callback: () => {
        this.note();
      }
    });
    this.addCommand({
      id: "generate-verbatim",
      name: "Generate Verbatim",
      // @ts-ignore
      callback: () => {
        this.verbatim();
      }
    });
    this.addCommand({
      id: "generate-action",
      name: "Generate Action",
      // @ts-ignore
      callback: () => {
        this.action();
      }
    });
    this.addCommand({
      id: "open-pdf",
      name: "Open PDF",
      // @ts-ignore
      callback: () => {
        const leaf = this.app.workspace.getLeaf();
        const file = this.getFileFromLeaf(leaf);
        const uuid = file.basename;
        const parent = file.parent.name;
        const cache = this.getFileCacheFromUUID(uuid);
        if (cache === void 0) {
          new import_obsidian.Notice(`Possible invalid frontmatter for: ${uuid}`);
          return;
        }
        const candidates = [];
        for (const l of cache.links) {
          const linktext = (0, import_obsidian.parseLinktext)(l.link);
          let linkedFile = void 0;
          try {
            linkedFile = this.app.metadataCache.getFirstLinkpathDest(
              linktext.path,
              file.path
            );
          } catch (e) {
            console.warn(
              `getFirstLinkpathDest failed for: ${linktext}`
            );
            continue;
          }
          if ((linkedFile == null ? void 0 : linkedFile.extension) === "pdf") {
            candidates.push(linkedFile);
          }
        }
        if (candidates.length === 0) {
          new import_obsidian.Notice(`No PDF in current view where found`);
          return;
        } else if (candidates.length > 1) {
          new import_obsidian.Notice(
            `More than one PDF in current view, opening first link`
          );
        }
        const candidate = candidates[0];
        if (!Helper.isUUID(candidate.parent.name)) {
          console.log(candidate.parent.name);
          new import_obsidian.Notice(`Invalid asset location: ${candidate.path}`);
          return;
        }
        if (candidate.parent.parent === void 0 || candidate.parent.parent.name !== "Assets") {
          new import_obsidian.Notice(`Invalid asset location: ${candidate.path}`);
          return;
        }
        const adapter = this.app.vault.adapter;
        const path = `${adapter.basePath}/${candidate.parent.path}`;
        const { spawn } = require("child_process");
        const command = `systemd-run --user --working-directory=${path} /usr/bin/zathura ${candidate.name}`;
        const child = spawn("/bin/sh", ["-lc", command], {
          stdio: ["ignore", "pipe", "pipe"]
          // ignore stdin => non interactif
        });
      }
    });
    this.addCommand({
      id: "clippy-the-clipper",
      name: "Clippy Clip",
      // @ts-ignore
      editorCallback: (editor) => {
        navigator.clipboard.readText().then((clipboardText) => {
          const text = clipboardText.replace(/[\r\n]+/g, "");
          console.log(text);
          let _name = void 0;
          let _fqdn = void 0;
          let file = void 0;
          let linkText = "";
          if (text.slice(0, 7) === "Assets/") {
            file = this.app.vault.getAbstractFileByPath(text);
            if (Helper.nilCheck(file)) {
              return;
            }
            _fqdn = file.path;
            _name = file.name;
            linkText = `[asset:: [[${_fqdn}| ${_name}]]]`;
          } else {
            let _id = void 0;
            try {
              _id = this.extractUUIDFromLink(text);
            } catch (e) {
              new import_obsidian.Notice(
                `Unaible to process clipboard: ${text} `
              );
              return;
            }
            file = this.getFileFromUUID(_id);
            Assert.True(
              file !== void 0,
              `getFileFromUUID: returned undefined for uuid: ${_id} `
            );
            const cache = this.getFileCacheFromUUID(_id);
            if (cache === void 0) {
              console.warn(
                `Possible invalid frontmatter for: ${_id} `
              );
              return;
            }
            _name = this.getResourceName(cache);
            _fqdn = _id;
            if (_name === void 0) {
              linkText = `[[${_fqdn}|${_name}]]`;
            } else {
              linkText = `[[${file.path.split("/").slice(0, -1)}/${_fqdn}|${_name}]]`;
            }
          }
          console.log(`linkText: "${linkText}"`);
          const cursor = editor.getCursor();
          const ch = Math.min(
            cursor.ch + 1,
            editor.getLine(cursor.line).length
          );
          editor.replaceRange(linkText, {
            line: cursor.line,
            ch
          });
        });
      }
    });
    this.addCommand({
      id: "copy-uuid",
      name: "Copy UUID",
      // @ts-ignore
      callback: async () => {
        const leaf = this.app.workspace.getLeaf();
        const file = this.getFileFromLeaf(leaf);
        const uuid = file.basename;
        const parent = file.parent.name;
        if (["Verbatim", "Notes", "Actions"].contains(parent)) {
          await navigator.clipboard.writeText(uuid);
        } else if (Helper.isUUID(parent) && file.parent.parent.name === "Assets") {
          await navigator.clipboard.writeText(file.path);
        }
      }
    });
    this.addCommand({
      id: "safe-delete",
      name: "Safe Delete",
      // @ts-ignore
      callback: () => {
        const file = this.app.workspace.getActiveFile();
        if (file === void 0) {
          return;
        }
        this.app.vault.delete(file);
      }
    });
    this.addCommand({
      id: "append-to-inbox",
      name: "Append to Inbox",
      // @ts-ignore
      callback: () => {
        const f = this.app.vault.getAbstractFileByPath("INBOX.md");
        if (f === void 0 || f === null) {
          console.warn(`file not found INBOX.md`);
          return;
        }
        const active = this.app.workspace.getLeaf();
        const root = active.parent;
        let found = false;
        let node = void 0;
        const emptyTabs = [];
        for (const leaf of root.children) {
          const file = this.getFileFromLeaf(leaf);
          if (file === void 0 || file === null) {
            emptyTabs.push(leaf);
            continue;
          }
          if (file.name === f.name) {
            found = true;
            node = leaf;
          }
        }
        if (!found) {
          if (emptyTabs.length > 0) {
            node = emptyTabs[0];
          } else {
            this.app.workspace.createLeafInParent(
              root,
              root.children.length + 1
            );
            node = root.children[root.children.length - 1];
          }
        }
        const editorAction = (node2) => {
          const editor = node2.view.sourceMode.cmEditor;
          editor.insertText("\n\n---\n\n", editor.lastLine());
          editor.setCursor(editor.lastLine(), 0);
        };
        if (this.app.workspace.getActiveFile() === null || this.app.workspace.getActiveFile().name !== "INBOX.md") {
          node.openFile(f, {
            active: true
          }).then((_) => editorAction(node));
        } else {
          editorAction(node);
        }
      }
    });
    this.app.workspace.onLayoutReady(() => {
      console.log("workspace - layout-ready");
      for (const f of this.app.vault.getFiles()) {
        const uuid = f.basename;
        if (!Helper.isUUID(uuid)) {
          continue;
        }
        this.vaultContentDict[uuid] = f;
      }
      this.reconcileAllHeadingAliases().catch((error) => {
        console.error("Unable to reconcile heading aliases", error);
      });
    });
    this.app.metadataCache.on(
      "changed",
      (file, data, cache) => {
        const uuid = file.basename;
        if (Helper.isUUID(uuid)) {
          this.vaultContentDict[uuid] = file;
        }
      }
    );
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        if (this.isHeadingAliasFile(file) || this.settings.managedHeadingAliases[file.path] !== void 0) {
          this.queueHeadingAliasSync(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (abstractFile, oldPath) => {
        if (!(abstractFile instanceof import_obsidian.TFile)) {
          const oldPrefix = `${oldPath}/`;
          const newPrefix = `${abstractFile.path}/`;
          for (const path of Object.keys(
            this.settings.managedHeadingAliases
          )) {
            if (!path.startsWith(oldPrefix)) {
              continue;
            }
            const nextPath = `${newPrefix}${path.slice(oldPrefix.length)}`;
            this.settings.managedHeadingAliases[nextPath] = this.settings.managedHeadingAliases[path];
            delete this.settings.managedHeadingAliases[path];
          }
          for (const [path, timer2] of this.headingAliasTimers) {
            if (path.startsWith(oldPrefix)) {
              window.clearTimeout(timer2);
              this.headingAliasTimers.delete(path);
            }
          }
          this.scheduleAliasSettingsSave();
          window.setTimeout(() => {
            this.reconcileAllHeadingAliases().catch((error) => {
              console.error(
                "Unable to reconcile heading aliases",
                error
              );
            });
          }, 0);
          return;
        }
        const timer = this.headingAliasTimers.get(oldPath);
        if (timer !== void 0) {
          window.clearTimeout(timer);
          this.headingAliasTimers.delete(oldPath);
        }
        const previousManagedAlias = this.settings.managedHeadingAliases[oldPath];
        if (previousManagedAlias !== void 0) {
          delete this.settings.managedHeadingAliases[oldPath];
          this.settings.managedHeadingAliases[abstractFile.path] = previousManagedAlias;
          this.scheduleAliasSettingsSave();
        }
        if (this.isHeadingAliasFile(abstractFile) || previousManagedAlias !== void 0) {
          this.queueHeadingAliasSync(abstractFile, 0);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (abstractFile) => {
        if (!(abstractFile instanceof import_obsidian.TFile)) {
          const prefix = `${abstractFile.path}/`;
          for (const path of Object.keys(
            this.settings.managedHeadingAliases
          )) {
            if (path.startsWith(prefix)) {
              delete this.settings.managedHeadingAliases[path];
            }
          }
          for (const [path, timer2] of this.headingAliasTimers) {
            if (path.startsWith(prefix)) {
              window.clearTimeout(timer2);
              this.headingAliasTimers.delete(path);
            }
          }
          this.scheduleAliasSettingsSave();
          return;
        }
        const timer = this.headingAliasTimers.get(abstractFile.path);
        if (timer !== void 0) {
          window.clearTimeout(timer);
          this.headingAliasTimers.delete(abstractFile.path);
        }
        this.setManagedHeadingAlias(abstractFile.path, void 0);
      })
    );
    this.app.workspace.on("active-leaf-change", () => {
      return this.sneakyTabRenamer(this.app);
    });
    this.app.workspace.on("quick-preview", () => {
      return this.sneakyTabRenamer(this.app);
    });
    this.app.workspace.on("resize", () => {
      return this.sneakyTabRenamer(this.app);
    });
  }
  sneakyTabRenamer(app) {
    const root = this.app.workspace.getLeaf().parent;
    for (const leaf of root.children) {
      const file = leaf.view.file;
      if (file === void 0) {
        continue;
      }
      const uuid = file.basename;
      const parent = file.parent.name;
      if (Helper.isUUID(parent) && file.parent.parent.name === "Assets") {
        return;
      }
      const cache = this.app.metadataCache.getFileCache(file);
      if (cache === void 0) {
        console.warn(`Possible invalid frontmatter for: ${uuid} `);
        return;
      }
      let text = this.getResourceName(cache);
      if (parent === "Actions") {
        if (!Helper.isDate(text)) {
          return;
        }
        if (text === void 0) {
          text = `(A) ${uuid} `;
        } else {
          const dt = new Date(text);
          text = `(A) ${dayShort[dt.getDay()]}.${dt.getDate()} ${monthShort[dt.getMonth()]}`;
        }
      } else if (parent === "Notes") {
        if (text === void 0) {
          text = `(N) ${uuid}`;
        } else {
          text = `(N) ${text}`;
        }
      } else if (parent === "Verbatim") {
        if (text === void 0) {
          text = `(N) ${uuid}`;
        } else {
          text = `(N) ${text}`;
        }
      } else {
        new import_obsidian.Notice(`Type undefined for file: ${file.path} `);
        return;
      }
      leaf.tabHeaderInnerTitleEl.innerText = text;
      leaf.tabHeaderInnerTitleEl.innerHTML = text;
    }
  }
  getResourceName(cache) {
    if (cache.headings === void 0) {
      return void 0;
    }
    if (cache.headings.length > 0 && cache.headings[0].level === 1) {
      return cache.headings[0].heading;
    } else {
      return cache.frontmatter.uuid;
    }
  }
  findResourceNamed(name, path) {
    const dv = this.app.plugins.plugins.dataview.api;
    const pages = dv.pages(`"${path}"`).where((page) => {
      const _uuid = page.file.name;
      const _cache = this.getFileCacheFromUUID(_uuid);
      if (_cache === void 0) {
        console.warn(`Possible invalid frontmatter for: ${_uuid} `);
        return false;
      }
      const _name = this.getResourceName(_cache);
      if (_name === void 0) {
        return false;
      }
      if (_name !== name) {
        return false;
      }
      return true;
    });
    if (pages.length === 0) {
      return "";
    } else {
      return pages[0].file.name;
    }
  }
  loadResourceNamed(name, path) {
    const dv = this.app.plugins.plugins.dataview.api;
    const pages = dv.pages(`"${path}"`).where((page) => {
      const uuid = page.file.name;
      const cache = this.getFileCacheFromUUID(uuid);
      if (cache === void 0) {
        console.warn(`Possible invalid frontmatter for: ${uuid} `);
        return false;
      }
      const _name = this.getResourceName(cache);
      if (_name === void 0) {
        return false;
      }
      if (_name !== name) {
        return false;
      }
      return true;
    });
    if (pages.length === 0) {
      return false;
    }
    if (pages.length > 1) {
      console.warn(`Multiple matches for: ${path}/${name}`);
    }
    this.openViewInNewTabIfNotOpened(`${path}/${pages[0].file.name}.md`);
    return true;
  }
  loadActionNamed(name) {
    return this.loadResourceNamed(name, Paths.Actions);
  }
  loadNoteNamed(name) {
    return this.loadResourceNamed(name, Paths.Notes);
  }
  onunload() {
    console.log("gonext - onunload()");
    for (const timer of this.headingAliasTimers.values()) {
      window.clearTimeout(timer);
    }
    this.headingAliasTimers.clear();
    if (this.aliasSettingsSaveTimer !== void 0) {
      window.clearTimeout(this.aliasSettingsSaveTimer);
      this.aliasSettingsSaveTimer = void 0;
      this.saveSettings().catch((error) => {
        console.error("Unable to save managed heading aliases", error);
      });
    }
    delete window.gonext;
  }
  async loadSettings() {
    var _a;
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
    this.settings.managedHeadingAliases = {
      ...(_a = this.settings.managedHeadingAliases) != null ? _a : {}
    };
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  action() {
    const dt = new Date();
    const note = {
      uuid: v4_default(),
      created_at: dt.toISOString(),
      path: "",
      data: ""
    };
    note.path = `${Paths.Actions}/${note.uuid}.md`;
    note.data = `---
uuid: "${note.uuid}"
created_at: "${note.created_at}"
---
# 
## content
`;
    const f = this.app.vault.create(note.path, note.data).then((f2) => {
      return f2;
    });
    const active = this.app.workspace.getLeaf();
    const root = active.parent;
    this.app.workspace.createLeafInParent(root, root.children.length + 1);
    const leaf = root.children[root.children.length - 1];
    f.then((file) => {
      leaf.openFile(file, { active: true });
    });
  }
  verbatim(name) {
    const dt = new Date();
    const note = {
      uuid: v4_default(),
      created_at: dt.toISOString(),
      path: "",
      data: ""
    };
    note.path = `${Paths.Verbatim}/${note.uuid}.md`;
    note.data = `---
uuid: "${note.uuid}"
created_at: "${note.created_at}"
---
# ${name}
## Content
`;
    if (name === void 0) {
      note.data = `---
uuid: "${note.uuid}"
created_at: "${note.created_at}"
---
# 
## Content
`;
    } else {
      note.data = `---
uuid: "${note.uuid}"
created_at: "${note.created_at}"
---
# ${name}
## Content
`;
    }
    const f = this.app.vault.create(note.path, note.data).then((f2) => {
      return f2;
    });
    const active = this.app.workspace.getLeaf();
    const root = active.parent;
    this.app.workspace.createLeafInParent(root, root.children.length + 1);
    const leaf = root.children[root.children.length - 1];
    f.then((file) => {
      leaf.openFile(file, { active: true });
    });
  }
  note(name) {
    const dt = new Date();
    const note = {
      uuid: v4_default(),
      created_at: dt.toISOString(),
      path: "",
      data: ""
    };
    note.path = `${Paths.Notes}/${note.uuid}.md`;
    if (name === void 0) {
      note.data = `---
uuid: "${note.uuid}"
created_at: "${note.created_at}"
---
# 
## Content
`;
    } else {
      note.data = `---
uuid: "${note.uuid}"
created_at: "${note.created_at}"
---
# ${name}
## Content
`;
    }
    const f = this.app.vault.create(note.path, note.data).then((f2) => {
      return f2;
    });
    const active = this.app.workspace.getLeaf();
    const root = active.parent;
    this.app.workspace.createLeafInParent(root, root.children.length + 1);
    const leaf = root.children[root.children.length - 1];
    f.then((file) => {
      leaf.openFile(file, { active: true });
    });
  }
};
var Helper = {
  nilCheck(val) {
    return val === void 0 || val === null;
  },
  roundToOneDecimal(val) {
    return Math.round(val * 10) / 10;
  },
  durationStringToSec(val) {
    if (val === void 0 || val.length === 0) {
      return 0;
    }
    const mult = val.slice(-1);
    let m = 0;
    if (mult === "h") {
      m = 60 * 60;
    } else if (mult === "m") {
      m = 60;
    } else if (mult === "d") {
      m = 24 * 60 * 60;
    } else if (mult == "w") {
      m = 24 * 60 * 60 * 7;
    } else {
      console.warn(`Unhandled case val: ${val}`);
      return void 0;
    }
    return m * parseInt(val.slice(0, -1));
  },
  msecToStringDuration(val) {
    const oneHourInMsec = 36e5;
    const oneDayInMsec = 864e5;
    if (val >= 24 * oneHourInMsec) {
      return String(Helper.roundToOneDecimal(val / oneDayInMsec)).padStart(
        2,
        "0"
      ) + " d";
    } else {
      return String(Helper.roundToOneDecimal(val / oneHourInMsec)).padStart(
        2,
        "0"
      ) + " h";
    }
  },
  isUUID(val) {
    if (typeof val !== "string") {
      return false;
    }
    return val.length === 36;
  },
  isDate(val) {
    if (val.length != 10) {
      return false;
    }
    const dt = new Date(val);
    if (dt.toString() === "Invalid Date") {
      return false;
    }
    return true;
  }
};
var ValidationError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "ValidationError";
  }
};
var Assert = {
  True(predicate, message, strict = true) {
    if (!predicate) {
      if (strict) {
        throw new ValidationError(message);
      } else {
        console.error(message);
      }
    }
  },
  False(predicate, message, strict = false) {
    if (predicate) {
      if (strict) {
        throw new ValidationError(message);
      } else {
        console.error(message);
      }
    }
  }
};
var Paths = {
  Actions: "Actions",
  Notes: "Notes",
  Verbatim: "Verbatim",
  Assets: "Assets",
  Tasks: "Actions"
};
